### ISSUE TITLE
Benchmarking scripts have extra pooling layers for model backbones?

### ISSUE THREAD

**Issue by faris-k** [lightly-ai/lightly#1042]
I'm noticing that in some of the benchmarking scripts, an extra pooling layer is sometimes added to ResNet backbones that already have one. Currently, all the models using ResNet-18 backbones in [imagenette_benchmark.py](https://github.com/lightly-ai/lightly/blob/master/docs/source/getting_started/benchmarks/imagenette_benchmark.py) and [imagenet100_benchmark.py](https://github.com/lightly-ai/lightly/blob/master/docs/source/getting_started/benchmarks/imagenet100_benchmark.py) are doing something like this:

https://github.com/lightly-ai/lightly/blob/fc252424afae73af54826d97b36042130522d025/docs/source/getting_started/benchmarks/imagenette_benchmark.py#L233-L238

But torchvision's ResNet-18 already includes a pooling layer. If you were to use `backbone` from above, you'd have two `AdaptiveAvgPool2d` layers at the end:

![image](https://user-images.githubusercontent.com/68213622/213531616-f1610f10-c582-4c59-ae8d-2e30a4184d34.png)

I know that the custom lightly ResNets don't have a pooling layer, so adding in a pooling layer works as you'd expect, so there's no such issue in the CIFAR-10 benchmarks:
```python
resnet = lightly.models.ResNetGenerator("resnet-18")
backbone = nn.Sequential(
    *list(resnet.children())[:-1],
    nn.AdaptiveAvgPool2d(1)
)
```
![image](https://user-images.githubusercontent.com/68213622/213532115-ca518e57-daff-405f-88cc-8568b1843cd5.png)

On that note, is there a reason the custom ResNet implementations don't include the pooling layer by default? Are there some scenarios where you wouldn't want to use pooling when using a ResNet backbone?

**Comment by guarin** [comment]
> I'm noticing that in some of the benchmarking scripts, an extra pooling layer is sometimes added to ResNet backbones that already have one.

Hi @faris-k, yes you are completely right, the extra pooling layer is in fact not needed. I believe this is a leftover from when we switched from the custom lightly ResNet to the torchvision ResNet. Note that the extra pooling layer does not affect the output.

> On that note, is there a reason the custom ResNet implementations don't include the pooling layer by default?

I highly recommend to not use the custom ResNet implementation (we also don't advocate it anymore in the examples). It was optimized to work well on small images. It actually does a pooling operation, but with a fixed kernel size intended for 32x32 pixel images. See here: https://github.com/lightly-ai/lightly/blob/master/lightly/models/resnet.py#L230

When doing the `nn.Sequential(*list(resnet.children())[:-1],  nn.AdaptiveAvgPool2d(1))` trick, the hardcoded pooling operation is removed because `resnet.forward` is not longer called, and the extra pooling layer has to be added.

> Are there some scenarios where you wouldn't want to use pooling when using a ResNet backbone?

If you just want a resnet for classification then you probably always want a pooling layer. There are some models which use the unpooled output, for example [VICRegL](https://docs.lightly.ai/self-supervised-learning/examples/vicregl.html), to get more localized information.

Hope that helps and thanks for bringing the issue up :)
