### ISSUE TITLE
SimSiam experiences

### ISSUE THREAD

**Issue by gabrieldernbach** [lightly-ai/lightly#134]
Thanks for sharing your application to satellite images in the tutorial.

Can you expand about the issues you had with applying simsiam to some real world datasets?
I am referring to your answer here: https://www.reddit.com/r/MachineLearning/comments/l154py/d_train_simsiam_on_cifar10_to_91_accuracy/

What issues did you encounter, what was the data?

**Comment by philippmwirth** [comment]
Hi, thanks for reaching out!

We've encountered several issues when working with SimSiam on real-world datasets. We had hoped that SimSiam could replace SimCLR in our command-line tool because it doesn't require negative samples. However, we found that:
- Augmentations and input size must be carefully chosen in order to keep the representations from collapsing
- SimSiam often needs a large number of epochs to yield good results (see [our benchmarks](https://docs.lightly.ai/getting_started/benchmarks.html#cifar10))
- In our [tutorial about satellite images](https://docs.lightly.ai/tutorials/package/tutorial_simsiam_esa.html) you can see that eventhough the representations didn't collapse, it can still be that they "collapse locally"
- We also observed that with small batch sizes (128), the results were not convincing on CIFAR-10.
- Getting SimSiam to work well may require a lot of effort in finetuning parameters

For these reasons, we stuck with using SimCLR or MoCo whenever possible. I hope this helps!
Let me know if you have any follow-up questions :) You can also ask them on our [discord](https://discord.com/invite/xvNJW94).
