### ISSUE TITLE
LARS optimizer

### ISSUE THREAD

**Issue by CHYjeremy** [lightly-ai/lightly#1378]
Hi authors of Lightning,

In "model" section of your documentation, almost all the method uses SGD optimizer,

However, most of these SOTA method uses LARS instead. May i ask that do you have any thoughts on this problem?

Thx!

**Comment by philippmwirth** [comment]
Hi @CHYjeremy, thanks for your question. We made the fundamental decision to not implement different optimizers that are used for self-supervised learning ourselves (at least for now) so as to not bloat the library unnecessarily. However, since we need LARS optimizer to reproduce Imagenet benchmarks, you can find an implementation of the `LARS` optimizer under
* `lightly/utils/lars.py`
For examples you can check out our Imagenet benchmarks under
* `benchmarks/imagenet/resnet50`
