### ISSUE TITLE
[Active Learning] add CLI to internal tests of AL loops

### ISSUE THREAD

**Issue by MalteEbner** [lightly-ai/lightly#140]
Add a command line interface to the following scripts:

- [x] https://github.com/lightly-ai/lightly/blob/develop_active_learning/tests/UNMOCKED_end2end_tests/test_al_step2.py
- [x] https://github.com/lightly-ai/lightly/blob/develop_active_learning/tests/UNMOCKED_end2end_tests/test_al_step3.py

**Comment by philippmwirth** [comment]
The requirements are simple: A user should not need to change the code in order to run the end-to-end test scripts. This makes it very simple to pull a branch and test whether the script works. Ideally, a user can set
- the path to the dataset
- the dataset id
- the query tag name
- the preselected tag name

when running the either of the two scripts. A sample command could look like this:
```bash
python test_al_step3.py this/is/my/dataset XYZ my-query-tag my-preselected-tag
```
Upon wrong usage, the user would be notified and an example command would be shown
```
python test_al_step3.py
> Wrong number of input arguments.
> Usage: python test_al_step3.py this/is/my/dataset XYZ my-query-tag my-preselected-tag
```

You can use `sys.argv` to access the arguments, see [this](https://realpython.com/python-command-line-arguments/).
