### ISSUE TITLE
Intuition behind n_local_views=0 in VICRegL

### ISSUE THREAD

**Issue by AndresPMD** [lightly-ai/lightly#1411]
Is there any intuition or reason why VICRegL uses n_local_views=0 as a default?

**Comment by guarin** [comment]
Hi! This is a very good question. We disable local views by default because they don't work well for ResNet backbones. Section 3.2 of the [paper](https://arxiv.org/pdf/2210.01571.pdf) explains this in more detail:

<img width="1086" alt="Screen Shot 2023-09-27 at 16 43 55" src="https://github.com/lightly-ai/lightly/assets/43336610/1a181aa4-4e95-417b-8052-28539e7f255a">

**Comment by guarin** [comment]
> Yes, I remember reading that on the paper. However, closing the local_views, basically is destroying the whole novelty of this paper on the locality, at least partially in ResNets.

I believe the novelty is mainly in using local features and the local criterion (see Fig 1. of the paper). Although for ResNets the local features are oftentimes not that local due to the large receptive field. Note that local views are independent of local features.

> Are you aware of have you tried out VICRegL with local_views in another backbone rather than ConvNeXt/ResNet?

I haven't tried it with other backbones, but it would be very interesting to do! Let me know if you try it out :)
