### ISSUE TITLE
docs: update contributing guide

### ISSUE THREAD

**Issue by SauravMaheshkar** [lightly-ai/lightly#1593]
Perhaps we should update our contributing guide. A few things I had in mind

- [x] Add a note about CI. Explain how the CI works and what workflows are expected to pass in the contributing process.
- [x] Possibly merge pre-commit instructions in the contributing guide.
- ~~Possibly? `CONTRIBUTING.md` -> `.github/CONTRIBUTING.md`~~.

**Comment by guarin** [comment]
>  Add a note about CI. Explain how the CI works and what workflows are expected to pass in the contributing process.

A note about the CI would definitely help, especially about when CI is triggered (new contributors etc.). Required workflows should be pretty easy to spot because they are marked "Required" in action checks overview, but would be good to mention this as well.

>  Possibly merge pre-commit instructions in the contributing guide.

Yep, sounds good to me.

>  Possibly? CONTRIBUTING.md -> .github/CONTRIBUTING.md.

Let's keep it on the top level, it makes the document easier to discover. It also makes it clear that all commands described in the document have to be executed from the top level.
