### ISSUE TITLE
Make output folder optional and easier to find

### ISSUE THREAD

**Issue by IgorSusmelj** [lightly-ai/lightly#2]
### Problem
When I use the CLI lightly it always creates a new output folder with a timestamp. This is good to make experiments reproducible. However, for some CLI commands such as `lightly-upload` or `lightly-download` creating folders seems not adding any value. 
Furthermore, I would rename the folder to something more descriptive than just `outputs`.

### Suggestion

- Make `lightly-upload` and `lightly-download` not create new output folders by default.
- Rename `outputs` to `lightly_outputs` or similar to make it clear which folders have been created by the lightly CLI.

**Comment by philippmwirth** [comment]
In my opinion it's better practice to always create an output directory because we use `hydra-core` to handle command-line arguments which will generate other output containing information about the executed command. This information can be very valuable and should not be hidden by default.

I think we should only address your second suggestion and rename `outputs` to `lightly_outputs`. See [this link](https://hydra.cc/docs/configure_hydra/workdir) for more information on how to do this.
