### ISSUE TITLE
NNCLR：queue_size

### ISSUE THREAD

**Issue by HBU-Lin-Li** [lightly-ai/lightly#542]
Hi,
In paper " With a Little Help From My Fridens：Nearest-Neighbor Contrastive Learning of Visual Representations", the queue size of the support is kept large enough so as to approximate the full dataset distribution in the embedding space. So the queue size is  seted by the dataste and the larger, the better?
If the dataset is pretty much, the queue size is larger ,  and the feature in queue may be inconsistent .

Thanks.

**Comment by IgorSusmelj** [comment]
I think the most important factor is that the number of samples in the queue (support set) is larger than the number of classes. If you have for example a dataset with 10 classes but only a queue of 5 you might end up picking nearest neighbors who are from another class. (e.g. a "car" gets replaced with its nearest neighbor that is now a "dog" because there are no cars in the queue of 5). 

In the paper, there is a table regarding the impact of the support set size. A larger set seems to lead to an increase in accuracy. But keep in mind that you also might eat up lots of memory space because you need to keep track of the whole support set.
![image](https://user-images.githubusercontent.com/1522766/139560680-04c93f6c-5d5c-4daf-860a-51e5c2dd25eb.png)

**Comment by HBU-Lin-Li** [comment]
I set the queue size and the dataset size to be consistent , but I have got a worse result.
