### ISSUE TITLE
Update ResNet to have optional `num_classes`

### ISSUE THREAD

**Issue by busycalibrating** [lightly-ai/lightly#60]
Currently, the ResNet implementation always adds a classification head but for almost all of the self supervised approaches, you only care about the actual backbone (and so you strip away this linear layer).

I'd propose to make the `num_classes` argument optional, and if `None`, omit the final linear layer so you only get the actual backbone. I can open a pull request for this if you're open to this.

Also, It looks like the library's implementation is not totally consistent with the default PyTorch ones (some missing max pools, different kernel sizes). I think a lot of people are likely to use the default PyTorch models for a lot of things, which would make the ResNets trained using Lightly incompatible. Would there be an interest in switching to the default PyTorch implementations?

**Comment by philippmwirth** [comment]
Yes, making `num_classes` optional is a good idea. Feel free to open the PR.

Regarding the ResNet implementation: For the future it would be good to change to the default PyTorch ResNet. However, we need to be careful to not break backwards compatability since we have certain pre-trained models and users may also have "old" checkpoints lying around. I'd suggest you open a new issue for this particular problem and we will discuss possible solutions there.
