### ISSUE TITLE
Any plans for self-supervised object detection?

### ISSUE THREAD

**Issue by faris-k** [lightly-ai/lightly#936]
Seeing as lightly has a ton of great models for self-supervised representation learning for "classification tasks," are there any plans in the future to implement methods for self-supervised object detection? Here's a link to a survey article and a few noteworthy papers in the area.

- A Survey of Self-Supervised and Few-Shot Object Detection: [https://arxiv.org/abs/2110.14711](https://arxiv.org/abs/2110.14711)
- DetCo: Unsupervised Contrastive Learning for Object Detection [https://arxiv.org/abs/2102.04803](https://arxiv.org/abs/2102.04803)
- DETReg: Unsupervised Pretraining with Region Priors for Object Detection [https://arxiv.org/abs/2106.04550](https://arxiv.org/abs/2106.04550)

I understand if end-to-end object detection methods are beyond the scope of lightly right now, but I'd figure I'd ask since it might be cool to see more of these types of models on lightly 😃

**Comment by guarin** [comment]
Hi @faris-k,

We are very much interested in self-supervised object detection and pretraining for object detection. We did not yet implement any methods because there does not seem to be a well defined standard on how to train such networks and how to do the data loading. This is in contrast with image classification where most models follow more or less the same training setup with only minor differences in the model architecture. We would love to explore self-supervised learning for object detection more in detail but it is currently not a priority.

Note that better image classification pretraining often also increases performance on object detection tasks. If you are interested in using a model available in lightly for training an object detector then please have a look at our [Detectron2 Tutorial](https://docs.lightly.ai/tutorials/package/tutorial_pretrain_detectron2.html)
